### PR TITLE
Add default include path to vlog/xvlog commands

### PR DESCRIPTION
**Pull request by ganoam**
The default include path is set to the DEPS directory for all
projects. `include directives should always specify the include path
relative to the DEPS directory.

### CODE REVIEW

**Comment by ljanyst** [comment]
LGTM, but please make sure you run `go fmt`.

**Comment by ganoam** [comment]
`go fmt` doesn't have any effect on this one. Is there anything in particular you want me to change?

**Comment by ljanyst** [comment]
Nothing. Looks good.

**Comment by ganoam** [comment]
Ok, thanks!

**Pull request merged**
